---
language: python
python:
    - "2.7"
    - "3.4"
install:
    # - pip install -e .
    # - pip install -U pytest
    # - pip install -U tox
    - pip install -U tox pytest pytest-cov coveralls
script:
    - make travis
after_success:
    - coveralls
